Fix a NoSuchMethodError loading OkHttp on Android (#8898)
The Sentry SDK assumes things in our public API that it
shouldn't be assuming. Oh well.

Closes: https://github.com/square/okhttp/issues/8826