* restores support for RoboVM platform. regression of #4266. RoboVM is android4 based runtime and it shares amount of classes from Android4. Its important to check for RoboVM platform before Android as RoboVM gets classified as Android and then will crash with `java.lang.NoClassDefFoundError: android/os/Build$VERSION`. RoboVMPlatform class is based on Android one. Unsupported entities were removed.